baseURL = "http://example.org/"
languageCode = "en-us"
title = "new blog"

[permalinks]
  blog = "/:filename/"
[params]
  homeText = " Lets get rolling "

[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    wieght = 1
  [[menu.main]]
    name = "Blog"
    pre = "edit"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 3
